[platformio]
default_envs = hw364a

[env:hw364a]
platform = espressif8266 @ 4.2.1
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_deps =
    adafruit/Adafruit SSD1306 @ ^2.5.13
    adafruit/Adafruit GFX Library @ ^1.11.11
build_flags =
    -D DCF77_ACTIVE_LOW=1
    -D DCF77_USE_INTERNAL_PULLUP=1
    -D DCF77_PON_ACTIVE_LOW=1
