# DCF77 RC8000 Console v2.5.4
# Copyright (c) 2026 Gianpaolo P.
# Licensed under the PolyForm Noncommercial License 1.0.0.
# Commercial use requires a separate written license from the copyright holder.
# See LICENSE and NOTICE.md.

name: PlatformIO build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install PlatformIO
        run: pip install platformio
      - name: Build v2.5.4
        run: pio run
